### ISSUE TITLE
Fix Object tutorial mistakes

### ISSUE THREAD

**Issue by Elfikurr** [prologin/gcc-contenus#23]
The `nager` function.
The fact that a dead pokemon can still attack its opponent.

**Comment by tanguysegarra** [comment]
The `nager` function has been fixed with issue #24 already.

**Comment by tanguysegarra** [comment]
OOP subject also needs an quick explanation on the `isinstance` method !

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/gcc/contenus/-/issues/23
