### ISSUE TITLE
Remove space strips in '03_reseau' exercise 5

### ISSUE THREAD

**Issue by n1tsu** [prologin/gcc-contenus#31]
## Remove space strip

* In exercise 5 there is a space strip at the beginning of each message (server ref)
* It breaks most of ascci art message which is a shame :disappointed: 
* We might want to remove it (extra care it was here to prevent abuse and space spam)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/gcc/contenus/-/issues/31
