### ISSUE TITLE
Clean up '03_reseau' and add missing information

### ISSUE THREAD

**Issue by n1tsu** [prologin/gcc-contenus#34]
## Clean up '03_reseau'

TP files (ref and server python files) are separated into `part_1`, `part_2` and `part_3` files but since the [subject](https://github.com/prologin/gcc-resources/blob/gh-pages/03_reseau.pdf) changed there is no more such parts and we want to rename and reorganize files.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/gcc/contenus/-/issues/34
