### ISSUE TITLE
Fix mistakes on 01 decouverte

### ISSUE THREAD

**Issue by Elfikurr** [prologin/gcc-contenus#46]
La différence exo-cours est pas assez claire
Indentation Python pas expliquée/pas claire
Exo4 trop flou, on ne sait pas ce qu'on doit faire
Merci @adangla 

Globalement, je trouve que les exos de ce TP sont vraiment pas clairs, et que ça vaudrait le coup de les refaire !

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/gcc/contenus/-/issues/46
