### ISSUE TITLE
01_decouverte_micropython: Feedback from GCC! Rennes

### ISSUE THREAD

**Issue by Nhqml** [prologin/gcc-contenus#65]
Here are some feedback from GCC! Rennes (December 2021):
* indentation is explained after being seen for the first times, event if it is not long after, some girls are confused by it when copy-pasting code samples
* page 9: maybe explain better how to achieve the progress bar exercise?
* page 12: typo --> replace "Tamagochi" with "Tamago**t**chi" (also in code sample)
* write some explanations about accelerometer (especially min/max values)

Maybe also:
* make a curated lists of methods to use. Some methods works weirdly or do not really work great with what we often do (IMO, methods like `accelerometer.current_gesture` of `accelerometer.was_gesture` should not be used to determine Micro::bit movement, instead use `accelerometer.get_x`, `accelerometer.get_y`, `accelerometer.get_z`)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/gcc/contenus/-/issues/65
