### ISSUE TITLE
Meilleure organisation du site des TPs GCC

### ISSUE THREAD

**Issue by Gregoire-perso** [prologin/gcc-contenus#70]
Bonjour à tous ! 

Lors des TP GCC weekend (je parle de ces TP car je n'ai pas eu l'occasion de faire des GCC semaine), les filles ont tendance à suivre l'ordre d'affichage des TP. Elles ont donc tendance à refaire le TP découverte python après avoir fait le TP découverte micropython, ainsi qu'à faire des TP python plutôt que des TP microbit. 
Je pense donc qu'il faudrait revoir un peu l'organisation de la page `tp.girlscancode.fr`, en divisant par exemple en deux sections "GCC week-end" et "GCC long". Cela permettrait aussi de mieux intégrer les refontes et les nouveaux TP GCC qui fonctionnent un peu plus sous forme d'évolution via des mini-projets. 

Je me permets de ping @rissson @AurelReb @Nhqml @Rookeur pour faire suite à cette proposition et en discuter. 

Bonne fin de journée à vous !

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/gcc/contenus/-/issues/70 :P
